hostname: aurora2pg
hostname_read_endpoint: aurora2pg-read
dns_format: ${EnvironmentName}.${DnsDomain}

cluster_port: 5432

master_login:
  username_ssm_param: /rds/AURORA_POSTGRES_MASTER_USERNAME
  password_ssm_param: /rds/AURORA_POSTGRES_MASTER_PASSWORD

cluster_parameters:
  timezone: "UTC"
